apiVersion: v1
stringData:
  db_user : "SECRETS_DB_USER"
  db_password: "SECRETS_DB_PASSWORD"
  db_host: "SECRETS_DB_HOST"
  db_name: "postgres"
  db_port: "5432"
kind: Secret
metadata:
  name: appsecrets