name: Deploy Micro Services

on:
  push:
    branches:
      - "develop"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: code checkout
      uses: actions/checkout@v2

    - name: install GCloud CLI
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true

    - name: Build and push docker images
      env: 
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" docker-compose.yml
        docker-compose up --build -d
        docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/backend/users:latest
        docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/backend/tests:latest
        docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/backend/proyects:latest
        docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/backend/auth:latest
      working-directory: backend/
    - name: Deploy to GKE
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud container clusters get-credentials autopilot-cluster-1 --region us-central1
        sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" deployment/k8s-deployment.yml
        kubectl apply -f deployment/
      working-directory: backend/
