name: Docker Compose Build and Test
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push to  Docker hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./backend/docker-compose.yml
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/clockbox:latest
       
  




