name: Docker Compose Build and Test
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME}}/daviddocker22/proyecto_2023

      - name: Docker push
        run: docker push ${{ secrets.DOCKER_USERNAME}}/daviddocker22/proyecto_2023

  




