name: Docker Compose Build and Test
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker-compose build
          docker tag my-docker-image:latest  ${{ secrets.DOCKERHUB_USER }}/daviddocker22/proyecto_2023
        working-directory: ./proyecto_1/backend/docker-compose.yml

      - name: Docker push
        run: docker push ${{ secrets.DOCKERHUB_USER}}/daviddocker22/proyecto_2023

  




