name: Docker Compose Build and Test
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v2
           
      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true
      #- name: Set up Docker Buildx
        #uses: docker/setup-buildx-action@v3

      #- name: Build Docker image
        #run: |
          #docker-compose up --build -d
          #working-directory: backend/
      - name: deploy to gke
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
            gcloud container clusters get-credentials autopilot-cluster-proyectofinal --region us-central1
            sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" backend/k8s-deployment.yml.yaml
            kubectl apply -f backend/k8s-deployment.yml.yaml
  




