name: Docker Compose Build and Test
on:
  push:
    branches:
      - develop
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Docker Compose services
        run: |
          docker-compose -f proyecto_1/backend/docker-compose.yml up -d

      - name: Run tests
        run: |
          # Ejecuta tus pruebas aquí
        

      - name: Stop Docker Compose services
        run: |
          docker-compose -f proyecto_1/backend/docker-compose.yml down
        





