name: Docker Compose Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Docker Compose services
        run: |
          docker-compose -f docker/docker-compose.yml up -d
        working-directory: ./proyecto_1 

      - name: Run tests
        run: |
          # Ejecuta tus pruebas aquí
        working-directory: ./proyecto_1 

      - name: Stop Docker Compose services
        run: |
          docker-compose -f docker/docker-compose.yml down
        working-directory: ./proyecto_1 





